# Generated by Django 5.2 on 2025-04-12 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=40)),
                ('telefono', models.BigIntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=199)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=59)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateField()),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cod_autorizacion', models.CharField(blank=True, max_length=35, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', models.IntegerField()),
                ('fecha', models.DateField()),
                ('detalle', models.CharField(max_length=100)),
                ('cod_autorizacion', models.CharField(blank=True, max_length=35, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BaseDatos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BaseDatos.usuario')),
                ('puntos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BaseDatos.usuario')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='NotaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=199)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.factura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('modelo', models.CharField(max_length=25)),
                ('stock', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.almacen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.notaventa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.rol'),
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.metododepago')),
            ],
        ),
        migrations.AddField(
            model_name='notaventa',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.transaccion'),
        ),
        migrations.CreateModel(
            name='DetalleDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.usuario')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.documento')),
            ],
            options={
                'unique_together': {('documento', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='HistorialCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.calificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.usuario')),
            ],
            options={
                'unique_together': {('calificacion', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='IngresoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mercaderia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.mercaderia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.producto')),
            ],
            options={
                'unique_together': {('producto', 'mercaderia')},
            },
        ),
        migrations.CreateModel(
            name='DetalleOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.oferta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.producto')),
            ],
            options={
                'unique_together': {('oferta', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('privilegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.privilegio')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.rol')),
            ],
            options={
                'unique_together': {('rol', 'privilegio')},
            },
        ),
        migrations.CreateModel(
            name='VentaOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('nota_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.notaventa')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.oferta')),
            ],
            options={
                'unique_together': {('oferta', 'nota_venta')},
            },
        ),
    ]
