# Generated by Django 5.2 on 2025-04-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
