# Generated by Django 5.2 on 2025-04-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatos', '0002_bitacora_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
