# Generated by Django 5.2 on 2025-04-12 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatos', '0003_alter_bitacora_fecha_alter_bitacora_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
