# Generated by Django 5.2 on 2025-04-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatos', '0004_alter_bitacora_fecha_alter_bitacora_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='detalleventa',
            unique_together={('producto', 'nota_venta')},
        ),
    ]
