# Generated by Django 5.2 on 2025-04-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatos', '0006_producto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
