# Generated by Django 5.2 on 2025-04-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatos', '0007_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
