# Generated by Django 5.2 on 2025-04-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatos', '0008_oferta_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaventa',
            name='documento_usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
